export const SAVE_AUTHOR = 'SAVE_AUTHOR';
export const GET_AUTHORS = 'GET_AUTHORS';
export const DELETE_AUTHOR = 'DELETE_AUTHOR';
export const DELETE_AUTHORS = 'DELETE_AUTHORS';
export const FETCH_AUTHORS_REQUEST = 'FETCH_AUTHORS_REQUEST';
export const FETCH_AUTHORS_SUCCESS = 'FETCH_AUTHORS_SUCCESS ';
export const FETCH_AUTHORS_FAILURE = 'FETCH_AUTHORS_FAILURE ';
