export const FETCH_COURSE_REQUEST = 'FETCH_COURSE_REQUEST';
export const FETCH_COURSE_SUCCESS = 'FETCH_COURSE_SUCCESS ';
export const FETCH_COURSE_FAILURE = 'FETCH_COURSE_SUCCESS ';
export const SAVE_COURSE = 'SAVE_COURSE';
export const DELETE_COURSE = 'DELETE_COURSE';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const GET_COURSES = 'GET_COURSES';
